### ISSUE TITLE
v.1.0.0 Checklist

### ISSUE THREAD

**Issue by 0x-r4bbit** [angular-translate/angular-translate#13]
- [x] Support for asynchronous loading of translations (#4)
- [x] Register storage provider support (#3)
- [x] Introducing `preferredLanguage()` (#29)
- [x] Automated changelog (#11)
- [x] Move examples to plunker (#5)
- [x] Teaching $translateProvider translation namespaces (#14)
- [x] Support for ng-pluralize (#15)
- [x] clarify final interpolation extension structure
- [x] update interpolation extensions accordingly
- [x] update to latest dependencies
- [x] prepare documentation for 1.0 release (update README)
- [x] making sure to update migration guide due to breaking changes
- [x] writing tutorial for website
- [x] clean up pending pull requests
- [x] release!
- [x] setup separate repositories for angular-translate extensions (https://github.com/PascalPrecht/angular-translate/issues/59)
- [x] missing translation handling (#45)
- [x] Add @knalli somehow as contributor, since he already did a great job by discussing features
- [x] Update repo to fit the angular module spec (names, structure etc.)
- [x] Check links in readme if they fit to new module name
- [x] Update wiki to fit to new module name (code examples, links etc.)
- [x] Update plunkers to fit new module and components name (also plunker tagging)
- [x] Update tests to run with new module name
- [x] Update package.json and component.json (bower.json) with new module name
- [x] Adding .bowerrc (#16)
- [x] Adding .jshintrc (#17)
- [x] Getting rid of provider folder
- [x] Documentation through code comments
- [x] Introducing ngmin (#20)
