### ISSUE TITLE
Roadmap 2.0

### ISSUE THREAD

**Issue by 0x-r4bbit** [angular-translate/angular-translate#322]
Here's a list of things that have to be done for 2.0, just to get an overview:
- [x] fixing fallback languages (https://github.com/PascalPrecht/angular-translate/issues/245) @PascalPrecht
- [x] Rewrite test suite (only partial loader tests are left) @PascalPrecht @Dwand
- [x] directive compilation `translate-compile` (https://github.com/PascalPrecht/angular-translate/pull/191) @Knalli
- [x] Change licence to MIT (https://github.com/PascalPrecht/angular-translate/issues/221) @PascalPrecht
- [ ] ~~rtl support (https://github.com/PascalPrecht/angular-translate/issues/227) @PascalPrecht~~
- [x] "ng-cloak" for angular-translate (https://github.com/PascalPrecht/angular-translate/issues/237) @PascalPrecht
- [ ] package repository for PM (npm, bower, NuGet) (https://github.com/PascalPrecht/angular-translate/issues/255)
- [x] Change fallback language during runtime (https://github.com/PascalPrecht/angular-translate/issues/313) @tspaeth
- [x] remove anonymous tables support (https://github.com/PascalPrecht/angular-translate/issues/314) @PascalPrecht
- [x] uses() -> use() (https://github.com/PascalPrecht/angular-translate/issues/315) @DWand 

Documentation:
- [x] updating "Useful Resources" (https://github.com/PascalPrecht/angular-translate/issues/292) @PascalPrecht
- [ ] how to unit test with async loaders @PascalPrecht
- [x] `$translate` is now async
- [x] fallback language handling and behaviour
- [x] Change docs about anonymous table support
- [x] uses() -> use()
- [x] translate-compile @Knalli
- [x] useSanitizedValues() (https://github.com/PascalPrecht/angular-translate/commit/fe94c1f) @knalli
- [x] events and $rootScope.$emit (https://github.com/PascalPrecht/angular-translate/commit/908496a17b95ee608c73303bf928749942babc1f) @PascalPrecht
- [x] determinePreferredLanguage() https://github.com/PascalPrecht/angular-translate/commit/7cbfabecc5c9d401a4f56792834be97a086b0aa2 @PascalPrecht
- [x] Docs for negoitation (https://github.com/PascalPrecht/angular- translate/commit/6bef6bd6a86fa4c5d9d4ed784b9749eab43caacb0) @pascalprecht
- [x] custom translate-value-\* attrs (https://github.com/PascalPrecht/angular-translate/commit/5c27467dc8e8724fa0288ea9ede5e39f54d352ec) @PascalPrecht
- [ ] grunt-angular-translate (@firehist)
- [ ] grunt-po2json-angular-translate (@DanielaValero)

Thinks I'd also like to get done:
- [x] moving repositories to org (needs investigation since I don't know if bower supports url redirects)
- [x] having a first version of the blog [THEME](there, I'd also like to announce 2.0) (@DanielaValero)

This is for team @angular-translate
